
-- 1	TÌM 20 KHÁCH HÀNG CÓ NHIỀU LOYALTY_POINTS NHẤT.	
SELECT *
FROM CUSTOMER
ORDER BY LOYALTY_POINTS DESC
LIMIT 20

-- 2	TÌM KHÁCH HÀNG CÓ NGÀY SINH TRONG KHOẢNG 1980–1990.
SELECT *
FROM CUSTOMER
WHERE EXTRACT(YEAR FROM BIRTH_DATE) BETWEEN 1980 AND 1990

-- 3	LIỆT KÊ 10 ĐƠN HÀNG GẦN NHẤT CỦA KÊNH BÁN WEB.	
SELECT *
FROM ORDERS
WHERE CHANNEL ILIKE 'WEB'
ORDER BY ORDER_DATE DESC
LIMIT 10

-- 4	TÌM KHÁCH HÀNG CÓ EMAIL CHỨA TỪ KHÓA 'YAHOO'.	
SELECT *
FROM CUSTOMER
WHERE EMAIL ILIKE '%YAHOO%'

-- 5	LẤY 5 ĐƠN HÀNG CÓ PHÍ VẬN CHUYỂN (SHIPPING_FEE) THẤP NHẤT.		
SELECT *
FROM ORDERS
ORDER BY SHIPPING_FEE
LIMIT 5

-- 6	TÌM KHÁCH HÀNG VIP (VIP_TIER <> 'NONE') VÀ SẮP XẾP THEO NGÀY TẠO MỚI NHẤT.		
SELECT *
FROM CUSTOMER
WHERE VIP_TIER <> 'NONE'
ORDER BY CREATED_AT DESC

-- 7	LIỆT KÊ 10 ĐƠN HÀNG CÓ TỔNG TIỀN (TOTAL_AMOUNT) TỪ 500 ĐẾN 1000.	
SELECT *
FROM ORDERS
WHERE TOTAL_AMOUNT BETWEEN 500 AND 1000
LIMIT 10

-- 8	TÌM KHÁCH HÀNG Ở THÀNH PHỐ BẮT ĐẦU BẰNG CHỮ S.	
SELECT *
FROM CUSTOMER
WHERE CITY ILIKE 'S%'

-- 9	LẤY 5 ĐƠN HÀNG CÓ TỔNG TIỀN LỚN NHẤT VÀ TRẠNG THÁI = PAID.	
SELECT *
FROM ORDERS
WHERE STATUS = 'PAID'
ORDER BY TOTAL_AMOUNT DESC
LIMIT 5

-- 10	LIỆT KÊ 10 KHÁCH HÀNG NAM CÓ NHIỀU LOYALTY_POINTS NHẤT.	
SELECT *
FROM CUSTOMER
WHERE GENDER ILIKE 'M'
ORDER BY LOYALTY_POINTS DESC
LIMIT 10

-- 11	ĐẾM SỐ ĐƠN HÀNG THEO TỪNG TRẠNG THÁI (STATUS).		
SELECT STATUS, COUNT(*) AS COUNT_ORDERS
FROM ORDERS
GROUP BY STATUS

-- 12	ĐẾM SỐ KHÁCH HÀNG THEO TỪNG THÀNH PHỐ (CITY).	
SELECT CITY, COUNT(*) AS COUNT_CUSTOMER
FROM CUSTOMER
GROUP BY CITY

-- 13	TÍNH TỔNG TOTAL_AMOUNT CỦA ĐƠN HÀNG THEO TỪNG PHƯƠNG THỨC THANH TOÁN (PAYMENT_METHOD).	
SELECT PAYMENT_METHOD, SUM(TOTAL_AMOUNT) AS TOTAL
FROM ORDERS
GROUP BY PAYMENT_METHOD

-- 14	TÍNH TỔNG SỐ LOYALTY_POINTS CỦA KHÁCH HÀNG THEO TỪNG CẤP ĐỘ VIP (VIP_TIER).	
SELECT VIP_TIER, SUM(LOYALTY_POINTS) AS TOTAL_LOYALTY_POINTS
FROM CUSTOMER
GROUP BY VIP_TIER

-- 15	TÍNH SỐ ĐƠN HÀNG THEO TỪNG KÊNH (CHANNEL).
SELECT CHANNEL, COUNT(*) AS COUNT_ORDERS
FROM ORDERS
GROUP BY CHANNEL

-- 16	TÌM CÁC THÀNH PHỐ CÓ TRÊN 50 KHÁCH HÀNG.
SELECT CITY, COUNT(*) AS COUNT_CUSTOMER
FROM CUSTOMER
GROUP BY CITY
HAVING COUNT(*) > 50

-- 17	TÌM PHƯƠNG THỨC THANH TOÁN CÓ TỔNG GIÁ TRỊ ĐƠN HÀNG TRÊN 10,000.		
SELECT PAYMENT_METHOD, SUM(TOTAL_AMOUNT) AS TOTAL
FROM ORDERS
GROUP BY PAYMENT_METHOD
HAVING SUM(TOTAL_AMOUNT) > 10000

-- 18	TÌM KÊNH BÁN CÓ TRUNG BÌNH TOTAL_AMOUNT > 300.			
SELECT CHANNEL, AVG(TOTAL_AMOUNT) AS AVG_TOTAL_AMOUNT
FROM ORDERS
GROUP BY CHANNEL
HAVING AVG(TOTAL_AMOUNT) > 300

-- 19	TÌM TRẠNG THÁI ĐƠN HÀNG CÓ NHIỀU HƠN 100 ĐƠN HÀNG.		
SELECT STATUS, COUNT(*) AS COUNT_ORDERS
FROM ORDERS
GROUP BY STATUS
HAVING COUNT(*) > 100

-- 20	TÌM CẤP ĐỘ VIP (VIP_TIER) CÓ TỔNG LOYALTY_POINTS > 50,000.
SELECT VIP_TIER, SUM(LOYALTY_POINTS) AS TOTAL_LOYALTY_POINTS
FROM CUSTOMER
GROUP BY VIP_TIER
HAVING SUM(LOYALTY_POINTS) > 50000

-- 21	TÌM 5 THÀNH PHỐ CÓ NHIỀU KHÁCH HÀNG NHẤT.		
SELECT CITY, COUNT(*) AS COUNT_CUSTOMER
FROM CUSTOMER
GROUP BY CITY
ORDER BY COUNT_CUSTOMER DESC
LIMIT 5

-- 22	TÌM 5 KHÁCH HÀNG CÓ NHIỀU ĐƠN HÀNG NHẤT.		
SELECT * FROM ORDERS

SELECT CUSTOMER_ID, COUNT(*) AS COUNT_ORDERS
FROM ORDERS
GROUP BY CUSTOMER_ID
ORDER BY COUNT_ORDERS DESC
LIMIT 5

-- 23	LIỆT KÊ 10 KHÁCH HÀNG CÓ TỔNG GIÁ TRỊ ĐƠN HÀNG CAO NHẤT.	
SELECT CUSTOMER_ID, SUM(TOTAL_AMOUNT) AS TOTAL_ORDERS
FROM ORDERS
GROUP BY CUSTOMER_ID
ORDER BY TOTAL_ORDERS DESC
LIMIT 10

-- 24	TÌM CÁC KHÁCH HÀNG CÓ TRUNG BÌNH ĐƠN HÀNG > 500.	
SELECT CUSTOMER_ID, AVG(TOTAL_AMOUNT) AS AVG_TOTAL
FROM ORDERS
GROUP BY CUSTOMER_ID
HAVING AVG(TOTAL_AMOUNT) > 500

-- 25	TÌM KÊNH BÁN HÀNG CÓ SỐ ĐƠN HÀNG HỦY (STATUS = CANCELLED) NHIỀU NHẤT.	
SELECT CHANNEL, COUNT(*) AS COUNT_ORDERS_CANCELLED
FROM ORDERS
WHERE STATUS = 'CANCELLED'
GROUP BY CHANNEL





